const ADMIN_PIN='1234',EXEC_KEY='pll_menu_ejecutivo',ORDERS_KEY='pll_pedidos',MENU_KEY='pll_menu_local',CONFIG_KEY='pll_config_estado';
let db=null,dbOk=false,orders=[],menu=[],estado={abierto:true,whatsapp:''};
let ejecutivo=JSON.parse(localStorage.getItem(EXEC_KEY)||'null')||{sopa:'Sopa de verduras',principios:['Arveja','Pepino'],proteinas:['Pollo a la plancha','Carne sudada','Carne molida'],precio:15000};
const $=id=>document.getElementById(id),money=n=>'$'+Math.round(n).toLocaleString('es-CO'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function loginAdmin(){if($('adminPin').value!==ADMIN_PIN)return toast('PIN incorrecto');sessionStorage.setItem('pll_admin_auth','1');$('pinGate').classList.add('hidden');$('adminApp').classList.remove('hidden');startAdmin()}
function startAdmin(){loadLocal();renderAll();if(window.db){db=window.db;dbOk=true;listenCloud()}}
function loadLocal(){orders=JSON.parse(localStorage.getItem(ORDERS_KEY)||'[]');menu=JSON.parse(localStorage.getItem(MENU_KEY)||'null')||[{id:'d1',nombre:'Bandeja Paisa',descripcion:'Frijoles, arroz, carne y acompañamientos.',categoria:'Fuertes',precio:28000,disponible:true},{id:'d2',nombre:'Sancocho de Gallina',descripcion:'Receta tradicional.',categoria:'Fuertes',precio:22000,disponible:true},{id:'d3',nombre:'Limonada de Coco',descripcion:'Refrescante.',categoria:'Bebidas',precio:8000,disponible:true}];estado={...estado,...JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}}
function listenCloud(){db.doc('config/estado').onSnapshot(s=>{if(s.exists)estado={...estado,...s.data()};renderEstado()});db.doc('config/ejecutivo').onSnapshot(s=>{if(s.exists)ejecutivo={...ejecutivo,...s.data()};localStorage.setItem(EXEC_KEY,JSON.stringify(ejecutivo));renderEjecutivoAdmin()});db.collection('pedidos').orderBy('creadoEn','desc').limit(100).onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()});db.collection('menu').onSnapshot(s=>{menu=s.docs.map(d=>({id:d.id,...d.data()}));renderMenuAdmin()})}
function renderAll(){renderEstado();renderEjecutivoAdmin();renderMenuAdmin();renderKds();renderSales()}
function renderEstado(){$('badgeEstado').textContent=estado.abierto?'Abierto':'Cerrado';$('badgeEstado').className='badge '+(estado.abierto?'ok':'closed');$('btnToggleEstado').textContent=estado.abierto?'Cerrar pedidos':'Abrir pedidos';$('inputWhatsapp').value=estado.whatsapp||'';$('btnToggleEstado').onclick=async()=>{estado.abierto=!estado.abierto;localStorage.setItem(CONFIG_KEY,JSON.stringify(estado));if(dbOk)await db.doc('config/estado').set(estado);renderEstado()}}
async function guardarWhatsapp(){let v=$('inputWhatsapp').value.replace(/\D/g,'');if(v&&!v.startsWith('57'))v='57'+v;estado.whatsapp=v;localStorage.setItem(CONFIG_KEY,JSON.stringify(estado));if(dbOk)await db.doc('config/estado').set(estado);toast('WhatsApp guardado')}
function renderEjecutivoAdmin(){$('listaEjecutivoAdmin').innerHTML=`<div class="executive-form"><label>Sopa</label><input id="execSopa" value="${esc(ejecutivo.sopa)}"><label>Principios, separados por coma</label><input id="execPrincipios" value="${esc(ejecutivo.principios.join(', '))}"><label>Proteínas, separadas por coma</label><input id="execProteinas" value="${esc(ejecutivo.proteinas.join(', '))}"><label>Precio</label><input id="execPrecio" type="number" value="${ejecutivo.precio}"></div>`}
async function guardarEjecutivoAdmin(){ejecutivo={sopa:$('execSopa').value.trim(),principios:$('execPrincipios').value.split(',').map(x=>x.trim()).filter(Boolean),proteinas:$('execProteinas').value.split(',').map(x=>x.trim()).filter(Boolean),precio:Number($('execPrecio').value)||0};localStorage.setItem(EXEC_KEY,JSON.stringify(ejecutivo));if(dbOk)await db.doc('config/ejecutivo').set(ejecutivo);toast('Menú ejecutivo actualizado')}
function renderKds(){const sorted=[...orders].sort((a,b)=>(b.creadoEn||0)-(a.creadoEn||0));$('kds').innerHTML=sorted.length?sorted.map(p=>{const time=p.horaCreacion||new Date(p.creadoEn||Date.now()).toLocaleTimeString('es-CO');return `<article class="kds-card"><div class="row between"><strong>${p.modalidad==='mesa'?'Mesa '+esc(p.mesa):'Domicilio'}</strong><time>${esc(time)}</time></div>${p.direccion?`<p class="muted">${esc(p.direccion)}</p>`:''}<ul>${p.items.map(i=>`<li>${i.cantidad}× ${esc(i.nombre)}${i.agregar?`<small>${esc(i.agregar)}</small>`:''}${i.quitar?.length?`<small>Sin: ${i.quitar.map(esc).join(', ')}</small>`:''}</li>`).join('')}</ul>${p.notas?`<p class="kds-note">Nota: ${esc(p.notas)}</p>`:''}<div class="row between"><strong>${money(p.total)}</strong><select onchange="cambiarEstado('${p.id}',this.value)">${['nuevo','en preparación','listo','entregado'].map(s=>`<option ${p.estadoPedido===s?'selected':''}>${s}</option>`).join('')}</select></div></article>`}).join(''):'<p class="muted">Sin pedidos todavía.</p>'}
async function cambiarEstado(id,value){const p=orders.find(x=>x.id===id);if(p)p.estadoPedido=value;localStorage.setItem(ORDERS_KEY,JSON.stringify(orders));if(dbOk)await db.collection('pedidos').doc(id).update({estadoPedido:value});renderKds()}
function todayOrders(){const key=new Date().toLocaleDateString('en-CA');return orders.filter(p=>new Date(p.creadoEn).toLocaleDateString('en-CA')===key)}
function renderSales(){const today=todayOrders(),total=today.reduce((s,p)=>s+p.total,0),counts={};today.forEach(p=>p.items.forEach(i=>counts[i.nombre]=(counts[i.nombre]||0)+i.cantidad));$('ventasHoy').textContent=money(total);$('pedidosHoy').textContent=today.length;$('corteLink').dataset.summary=Object.entries(counts).map(([n,c])=>`${c}x ${n}`).join(' · ')}
function corteCaja(){const today=todayOrders(),total=today.reduce((s,p)=>s+p.total,0),counts={};today.forEach(p=>p.items.forEach(i=>counts[i.nombre]=(counts[i.nombre]||0)+i.cantidad));const date=new Date().toLocaleDateString('es-CO',{day:'2-digit',month:'long'}),summary=`*CORTE DE CAJA · PANCITA LLENA*\nFecha: ${date}\nPedidos: ${today.length}\n\n*VENTAS POR PLATO*\n${Object.entries(counts).map(([n,c])=>`• ${c}x ${n}`).join('\n')||'Sin ventas'}\n\n*TOTAL DEL DÍA: ${money(total)}*`,num=(estado.whatsapp||'').replace(/\D/g,''),link=`https://wa.me/${num}?text=${encodeURIComponent(summary)}`;$('corteLink').innerHTML=`<a class="btn wide" href="${link}" target="_blank" rel="noopener">Abrir WhatsApp con el corte</a>`}
function renderMenuAdmin(){$('listaAdminMenu').innerHTML=menu.map(d=>`<div class="admin-dish"><strong>${esc(d.nombre)}</strong><div class="row"><input id="n-${d.id}" value="${esc(d.nombre)}"><input id="p-${d.id}" type="number" value="${d.precio}"><button class="btn secondary small" onclick="guardarPlatoAdmin('${d.id}')">Guardar</button></div></div>`).join('')}
async function guardarPlatoAdmin(id){const d=menu.find(x=>x.id===id);d.nombre=$('n-'+id).value;d.precio=Number($('p-'+id).value)||0;localStorage.setItem(MENU_KEY,JSON.stringify(menu));if(dbOk)await db.collection('menu').doc(id).update({nombre:d.nombre,precio:d.precio});toast('Plato actualizado')}
async function agregarPlatoAdmin(){const nombre=$('nuevoNombre').value.trim();if(!nombre)return toast('Ponle un nombre al plato');const d={id:'local-'+Date.now(),nombre,descripcion:$('nuevoDesc').value.trim(),categoria:$('nuevoCat').value.trim()||'General',precio:Number($('nuevoPrecio').value)||0,ingredientes:$('nuevoIngredientes').value.split(',').map(x=>x.trim()).filter(Boolean),disponible:true};menu.push(d);localStorage.setItem(MENU_KEY,JSON.stringify(menu));if(dbOk){const{id,...data}=d;await db.collection('menu').add(data)}renderMenuAdmin();toast('Plato agregado')}
if(sessionStorage.getItem('pll_admin_auth')){$('pinGate').classList.add('hidden');$('adminApp').classList.remove('hidden');startAdmin()}$('adminPin').addEventListener('keydown',e=>{if(e.key==='Enter')loginAdmin()});window.addEventListener('storage',e=>{if(e.key===ORDERS_KEY||e.key===EXEC_KEY||e.key===CONFIG_KEY){loadLocal();renderAll()}});
