const CART_KEY='pll_carrito', MODO_KEY='pll_modalidad', EXEC_KEY='pll_menu_ejecutivo', ORDERS_KEY='pll_pedidos', CONFIG_KEY='pll_config_estado', DEFAULT_WHATSAPP='573025471754';
let db=null,dbOk=false,menu=[],pedidos=[],estado={abierto:true,whatsapp:''};
let carrito=JSON.parse(localStorage.getItem(CART_KEY)||'[]');
let modo=JSON.parse(localStorage.getItem(MODO_KEY)||'null');
let ejecutivo=JSON.parse(localStorage.getItem(EXEC_KEY)||'null')||{
  sopa:'Sopa de verduras', principios:['Arveja','Pepino'], proteinas:['Pollo a la plancha','Carne sudada','Carne molida'], bebidas:[], precio:15000
};
let ejecutivoSeleccion={sopa:'',principio:'',proteina:'',bebida:''};
let adminToques=0,adminToqueTimer=null;
const DOMINGO=[
  {nombre:'Bandeja Paisa',precio:25000},{nombre:'Cachama frita o sudada',precio:21000},
  {nombre:'Lengua en salsa',precio:25000},{nombre:'Pechuga a la plancha',precio:21000},
  {nombre:'Bagre sudado o frito',precio:25000},{nombre:'Pernil frito o en salsa',precio:20000},
  {nombre:'Arroz con pollo',precio:18000},{nombre:'Pechuga gratinada',precio:25000},
  {nombre:'Alitas BBQ',precio:20000},{nombre:'Lomo de cerdo',precio:21000}
];
const MENU_DEMO=[
  {id:'d1',nombre:'Bandeja Paisa',descripcion:'Frijoles, arroz, carne asada, chicharrón, huevo, plátano y aguacate.',categoria:'Fuertes',precio:28000,ingredientes:['frijoles','arroz','carne','chicharrón','huevo','plátano'],disponible:true},
  {id:'d2',nombre:'Sancocho de Gallina',descripcion:'Receta tradicional con yuca, plátano, mazorca y cilantro.',categoria:'Fuertes',precio:22000,ingredientes:['gallina','yuca','plátano','mazorca','cilantro'],disponible:true},
  {id:'d3',nombre:'Limonada de Coco',descripcion:'Refrescante, cremosa y preparada al momento.',categoria:'Bebidas',precio:8000,ingredientes:['limón','coco','azúcar','hielo'],disponible:true}
];
const $=id=>document.getElementById(id);
const money=n=>'$'+Math.round(n).toLocaleString('es-CO');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function guardarCarritoLS(){localStorage.setItem(CART_KEY,JSON.stringify(carrito))}
function guardarModoLS(){localStorage.setItem(MODO_KEY,JSON.stringify(modo))}
function getWhatsAppNumber(){const saved=JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}').whatsapp||estado.whatsapp||DEFAULT_WHATSAPP;let digits=String(saved).replace(/\D/g,'');if(!digits)digits=DEFAULT_WHATSAPP;if(!digits.startsWith('57'))digits='57'+digits.slice(-10);return digits}
async function init(){
  db=window.db||null;
  dbOk=!!db;
  if(dbOk){
    db.collection('menu').onSnapshot(s=>{menu=s.docs.map(d=>({id:d.id,...d.data()}));renderMenu();renderAdminMenu()},()=>{menu=MENU_DEMO;renderMenu();renderAdminMenu()});
    db.doc('config/estado').onSnapshot(s=>{estado=s.exists?s.data():{abierto:true,whatsapp:''};renderEstado()});
    db.doc('config/ejecutivo').onSnapshot(s=>{if(s.exists){ejecutivo={...ejecutivo,...s.data()};guardarEjecutivoLS()}renderEjecutivo();renderAdminEjecutivo()});
    db.collection('pedidos').orderBy('creadoEn','desc').limit(50).onSnapshot(s=>{pedidos=s.docs.map(d=>({id:d.id,...d.data()}));renderPedidos()});
    const snap=await db.collection('menu').get();if(snap.empty)for(const p of MENU_DEMO){const{id,...rest}=p;await db.collection('menu').add(rest)}
  }else{$('estadoTexto').textContent='Modo local · listo para pedir';menu=JSON.parse(localStorage.getItem('pll_menu_local')||'null')||MENU_DEMO;renderMenu();renderAdminMenu();renderEjecutivo();renderAdminEjecutivo();renderDomingo();renderEstado()}
  estado={...estado,...JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')};
  ejecutivo={...ejecutivo,...JSON.parse(localStorage.getItem(EXEC_KEY)||'{}')};
  renderDomingo();renderEjecutivo();renderAdminEjecutivo();detectarModalidadURL();renderCarrito();
  window.addEventListener('storage',e=>{if(e.key===EXEC_KEY){ejecutivo={...ejecutivo,...JSON.parse(e.newValue||'{}')};renderEjecutivo()}if(e.key===CONFIG_KEY){estado={...estado,...JSON.parse(e.newValue||'{}')};renderEstado()}if(e.key==='pll_menu_local'){menu=JSON.parse(e.newValue||'null')||MENU_DEMO;renderMenu()}})
}
init();
document.querySelectorAll('.menu-tabs button').forEach(b=>b.addEventListener('click',()=>{
  document.querySelectorAll('.menu-tabs button').forEach(x=>x.classList.remove('active'));
  document.querySelectorAll('.menu-view').forEach(x=>x.classList.add('hidden'));
  b.classList.add('active');$('menuView-'+b.dataset.menuView).classList.remove('hidden');
}));
function detectarModalidadURL(){const p=new URLSearchParams(location.search),mesa=p.get('mesa');if(mesa&&!modo){modo={tipo:'mesa',mesa};guardarModoLS()}mostrarPasoSegunModo()}
function mostrarPasoSegunModo(){['pasoModalidad','pasoMesa','pasoDireccion','menuWrap'].forEach(id=>$(id).classList.add('hidden'));if(!modo){$('pasoModalidad').classList.remove('hidden');return}$('menuWrap').classList.remove('hidden');$('modalidadResumen').textContent=modo.tipo==='mesa'?`Mesa ${modo.mesa}`:`Domicilio · ${modo.direccion}`;if(modo.tipo==='domicilio'){$('inputTelefono').value=modo.telefono||''}renderCarrito()}
function elegirModalidad(tipo){['pasoModalidad','pasoMesa','pasoDireccion'].forEach(id=>$(id).classList.add('hidden'));if(tipo==='mesa'){$('inputMesa').value='';$('pasoMesa').classList.remove('hidden')}else $('pasoDireccion').classList.remove('hidden')}
function confirmarMesa(){const v=$('inputMesa').value;if(!v)return toast('Ingresa un número de mesa');modo={tipo:'mesa',mesa:v};guardarModoLS();mostrarPasoSegunModo()}
function confirmarDireccion(){const v=$('inputDireccion').value.trim();const t=$('inputTelefono').value.trim();if(!v)return toast('Ingresa la dirección exacta');if(!t)return toast('Ingresa tu número de teléfono');modo={tipo:'domicilio',direccion:v,telefono:t};guardarModoLS();mostrarPasoSegunModo()}
function volverModalidad(){modo=null;guardarModoLS();mostrarPasoSegunModo()}
function renderMenu(){const cats=[...new Set(menu.map(m=>m.categoria||'General'))];$('menuList').innerHTML=cats.map(cat=>`<h2 class="menu-category">${escapeHTML(cat)}</h2>${menu.filter(m=>(m.categoria||'General')===cat).map(dishCardHTML).join('')}`).join('')}
function renderDomingo(){$('menuView-domingo').innerHTML=`<div class="menu-intro"><p class="eyebrow">Domingo de Pancita Llena</p><h2>Bandejas especiales y sopas caseras</h2><p class="muted">Una carta fija para disfrutar el domingo, con el sabor de siempre.</p></div><h2 class="menu-category">Bandejas especiales</h2>${DOMINGO.map(d=>`<article class="dish-card"><div><h3>${escapeHTML(d.nombre)}</h3><p class="dish-desc">Preparado al momento con acompañamientos de la casa.</p><div class="dish-actions"><button class="btn small" onclick="addFixed('${escapeHTML(d.nombre)}',${d.precio})">Agregar</button></div></div><span class="dish-price">${money(d.precio)}</span></article>`).join('')}<h2 class="menu-category">Sopas</h2><article class="dish-card"><div><h3>Ajiaco Santafereño</h3><p class="dish-desc">Acompañado de arroz y tajadas.</p><button class="btn small" onclick="addFixed('Ajiaco Santafereño',12000)">Agregar</button></div><span class="dish-price">$12.000</span></article><article class="dish-card"><div><h3>Sopa del día</h3><p class="dish-desc">Preparada con harina de maíz.</p><button class="btn small" onclick="addFixed('Sopa del día',5000)">Agregar</button></div><span class="dish-price">$5.000</span></article><p class="menu-note">Domicilio y contenedor tienen un costo adicional de $1.000 cada uno.</p>`}
function optionButtons(items,group){return items.map(item=>`<button type="button" class="option-button ${ejecutivoSeleccion[group]===item?'selected':''}" onclick="seleccionarEjecutivo('${group}','${escapeHTML(item).replace(/'/g,"&#39;")}')">${escapeHTML(item)}</button>`).join('')}
function renderEjecutivo(){$('menuView-ejecutivo').innerHTML=`<div class="menu-intro"><p class="eyebrow">Lunes a sábado</p><h2>Arma tu menú ejecutivo</h2><p class="muted">Selecciona una opción de cada grupo antes de agregarlo.</p></div><div class="executive-card"><div class="executive-price">${money(ejecutivo.precio)}</div><div class="executive-choice"><strong>Sopa</strong><div class="option-list">${optionButtons([ejecutivo.sopa],'sopa')}</div></div><div class="executive-choice"><strong>Principio</strong><div class="option-list">${optionButtons(ejecutivo.principios,'principio')}</div></div><div class="executive-choice"><strong>Proteína</strong><div class="option-list">${optionButtons(ejecutivo.proteinas,'proteina')}</div></div><div class="executive-choice"><strong>Bebida</strong><div class="option-list">${optionButtons(ejecutivo.bebidas||[],'bebida')}</div></div><button class="btn wide" onclick="addExecutive()">Agregar menú ejecutivo</button></div>`}
function seleccionarEjecutivo(group,value){ejecutivoSeleccion[group]=value;renderEjecutivo()}
function addExecutive(){if(!estado.abierto)return toast('Ahora mismo no estamos recibiendo pedidos');if(!ejecutivoSeleccion.sopa||!ejecutivoSeleccion.principio||!ejecutivoSeleccion.proteina||!ejecutivoSeleccion.bebida)return toast('Elige sopa, principio, proteína y bebida');const detalle=`Sopa: ${ejecutivoSeleccion.sopa} · Principio: ${ejecutivoSeleccion.principio} · Proteína: ${ejecutivoSeleccion.proteina} · Bebida: ${ejecutivoSeleccion.bebida}`;agregarAlCarrito({id:'executive-'+Date.now(),nombre:'Menú ejecutivo',precio:ejecutivo.precio},1,[],detalle);toast('Menú ejecutivo agregado')}
function addFixed(nombre,precio){if(!estado.abierto)return toast('Ahora mismo no estamos recibiendo pedidos');agregarAlCarrito({id:'fixed-'+nombre,nombre,precio},1,[],'');toast(`${nombre} agregado`)}
function dishCardHTML(d){const ing=d.ingredientes||[],available=d.disponible!==false;return `<article class="dish-card"><div><h3>${escapeHTML(d.nombre)}</h3><p class="dish-desc">${escapeHTML(d.descripcion||'')}</p><div class="dish-actions">${available?`<button class="btn secondary small" onclick="toggleCustom('${d.id}')">Personalizar</button><button class="btn small" onclick="addQuick('${d.id}')">Agregar</button>`:'<span class="badge closed">Agotado por hoy</span>'}</div></div><span class="dish-price">${money(d.precio)}</span>${available?`<div class="custom-panel" id="custom-${d.id}">${ing.length?`<label>Quitar ingredientes</label><div class="chip-list">${ing.map((i,n)=>`<label class="chip"><input type="checkbox" id="q-${d.id}-${n}"> ${escapeHTML(i)}</label>`).join('')}</div>`:''}<label>Agregar extras</label><input type="text" id="extra-${d.id}" placeholder="Ej: sin picante, extra queso"><div class="row between"><div class="row qty"><button onclick="stepQty('${d.id}',-1)">−</button><span id="qty-${d.id}">1</span><button onclick="stepQty('${d.id}',1)">+</button></div><button class="btn small" onclick="addCustom('${d.id}')">Agregar personalizado</button></div></div>`:''}</article>`}
function toggleCustom(id){$('custom-'+id).classList.toggle('open')}
function stepQty(id,delta){const e=$('qty-'+id);e.textContent=Math.max(1,parseInt(e.textContent)+delta)}
function addQuick(id){if(!estado.abierto)return toast('Ahora mismo no estamos recibiendo pedidos');const d=menu.find(m=>m.id===id);agregarAlCarrito(d,1,[],'');toast(`${d.nombre} agregado`)}
function addCustom(id){if(!estado.abierto)return toast('Ahora mismo no estamos recibiendo pedidos');const d=menu.find(m=>m.id===id),ing=d.ingredientes||[],quitar=ing.filter((i,n)=>$(`q-${id}-${n}`)?.checked),extra=$('extra-'+id).value.trim(),cant=parseInt($('qty-'+id).textContent)||1;agregarAlCarrito(d,cant,quitar,extra);$('custom-'+id).classList.remove('open');toast(`${d.nombre} agregado`)}
function agregarAlCarrito(d,cantidad,quitar,agregar){carrito.push({menuId:d.id,nombre:d.nombre,precio:d.precio,cantidad,quitar,agregar});guardarCarritoLS();renderCarrito()}
function renderCarrito(){const total=carrito.reduce((s,i)=>s+i.precio*i.cantidad,0),cant=carrito.reduce((s,i)=>s+i.cantidad,0);$('carritoResumen').textContent=`${cant} ${cant===1?'plato':'platos'}`;$('carritoTotal').textContent=money(total);$('carritoTotalSheet').textContent=money(total);$('carritoBar').classList.toggle('hidden',!carrito.length);$('carritoItems').innerHTML=carrito.length?carrito.map((i,n)=>`<div class="cart-item"><div><strong>${i.cantidad}× ${escapeHTML(i.nombre)}</strong>${i.quitar?.length?`<small>Sin: ${i.quitar.map(escapeHTML).join(', ')}</small>`:''}${i.agregar?`<small>Extra: ${escapeHTML(i.agregar)}</small>`:''}</div><div class="row"><span>${money(i.precio*i.cantidad)}</span><button class="btn ghost small" onclick="quitarDelCarrito(${n})" aria-label="Quitar ${escapeHTML(i.nombre)}">×</button></div></div>`).join(''):'<p class="muted">Tu carrito está vacío.</p>'}
function quitarDelCarrito(i){carrito.splice(i,1);guardarCarritoLS();renderCarrito()}
function abrirCarrito(){$('overlayCarrito').classList.add('open');$('whatsappLinkWrap').innerHTML='';$('pedidoNotas').value=''}
function cerrarCarrito(){$('overlayCarrito').classList.remove('open')}
async function confirmarPedido(){if(!carrito.length)return toast('Agrega al menos un plato');if(!modo)return toast('Selecciona primero cómo vas a pedir');if(!estado.abierto)return toast('Ahora mismo no estamos recibiendo pedidos');const now=new Date(),createdAt=now.getTime(),date=now.toLocaleDateString('es-CO',{day:'2-digit',month:'long'}),time=now.toLocaleTimeString('es-CO'),notes=$('pedidoNotas').value.trim(),total=carrito.reduce((s,i)=>s+i.precio*i.cantidad,0),pedido={modalidad:modo.tipo,mesa:modo.mesa||null,direccion:modo.direccion||null,telefono:modo.telefono||null,items:carrito.map(i=>({nombre:i.nombre,cantidad:i.cantidad,precio:i.precio,quitar:i.quitar||[],agregar:i.agregar||''})),notas:notes,total,estadoPedido:'nuevo',creadoEn:createdAt,horaCreacion:time,fechaCreacion:now.toLocaleDateString('es-CO')};const localOrders=JSON.parse(localStorage.getItem(ORDERS_KEY)||'[]');localOrders.unshift(pedido);localStorage.setItem(ORDERS_KEY,JSON.stringify(localOrders.slice(0,100)));if(dbOk)try{await db.collection('pedidos').add(pedido)}catch(e){toast('Pedido guardado localmente; revisa WhatsApp')}const lines=carrito.map(i=>`• ${i.cantidad} x ${i.nombre}\n  Valor unitario: ${money(i.precio)}\n  Subtotal: ${money(i.precio*i.cantidad)}${i.quitar?.length?`\n  Sin: ${i.quitar.join(', ')}`:''}${i.agregar?`\n  Detalle: ${i.agregar}`:''}`).join('\n\n'),identificacion=modo.tipo==='mesa'?`*MESA: ${modo.mesa}*`:`*DOMICILIO*\nDirección: ${modo.direccion}\nTeléfono del cliente: ${modo.telefono}`,message=`*PEDIDO · PANCITA LLENA*\n${identificacion}\n\nFecha: ${date}\nHora: ${time}\n\n*PLATOS ORDENADOS*\n${lines}\n\n*TOTAL: ${money(total)}*${notes?`\n\n*OBSERVACIONES*\n${notes}`:''}`,msg=encodeURIComponent(message),rawPhone=(estado.whatsapp||DEFAULT_WHATSAPP||'').replace(/\D/g,''),num=rawPhone?(rawPhone.startsWith('57')?rawPhone:`57${rawPhone}`):'',link=num?`https://wa.me/${num}?text=${msg}`:`https://wa.me/?text=${msg}`;window.open(link,'_blank');cerrarCarrito();$('pedidoNotas').value='';carrito=[];guardarCarritoLS();renderCarrito();toast('¡Pedido enviado! Revisa WhatsApp')}
function renderEstado(){if(!$('estadoTexto'))return;$('estadoTexto').textContent=estado.abierto?'Recibiendo pedidos':'Cerrado por ahora'}
async function guardarWhatsapp(){const v=$('inputWhatsapp').value.trim();estado.whatsapp=v;localStorage.setItem(CONFIG_KEY,JSON.stringify(estado));if(dbOk)await db.doc('config/estado').update({whatsapp:v});toast('Número guardado')}
function guardarEjecutivoLS(){localStorage.setItem(EXEC_KEY,JSON.stringify(ejecutivo))}
function renderAdminEjecutivo(){if(!$('listaEjecutivoAdmin'))return}
async function guardarEjecutivo(){const data={sopa:$('execSopa').value.trim()||'Sopa del día',principios:$('execPrincipios').value.split(',').map(s=>s.trim()).filter(Boolean),proteinas:$('execProteinas').value.split(',').map(s=>s.trim()).filter(Boolean),bebidas:($('execBebidas')?.value||'').split(',').map(s=>s.trim()).filter(Boolean),precio:Number($('execPrecio').value)||0};ejecutivo=data;guardarEjecutivoLS();if(dbOk)await db.doc('config/ejecutivo').set(data);renderEjecutivo();renderAdminEjecutivo();toast('Menú ejecutivo actualizado')}
function renderAdminMenu(){if(!$('listaAdminMenu'))return}
async function guardarPlato(id){const d=menu.find(m=>m.id===id),data={nombre:$('an-'+id).value,descripcion:$('ad-'+id).value,categoria:$('ac-'+id).value||'General',precio:Number($('ap-'+id).value)||0,disponible:$('av-'+id).checked};if(dbOk)await db.collection('menu').doc(id).update(data);else{Object.assign(d,data);renderMenu();renderAdminMenu()}toast('Plato actualizado')}
async function eliminarPlato(id){if(dbOk)await db.collection('menu').doc(id).delete();else{menu=menu.filter(m=>m.id!==id);renderMenu();renderAdminMenu()}toast('Plato eliminado')}
async function agregarPlato(){const nombre=$('nuevoNombre').value.trim();if(!nombre)return toast('Ponle un nombre al plato');const data={nombre,descripcion:$('nuevoDesc').value.trim(),categoria:$('nuevoCat').value.trim()||'General',precio:Number($('nuevoPrecio').value)||0,ingredientes:$('nuevoIngredientes').value.split(',').map(s=>s.trim()).filter(Boolean),disponible:true};if(dbOk)await db.collection('menu').add(data);else{data.id='local-'+Date.now();menu.push(data);renderMenu();renderAdminMenu()}['nuevoNombre','nuevoDesc','nuevoCat','nuevoPrecio','nuevoIngredientes'].forEach(id=>$(id).value='');toast('Plato agregado al menú')}
function renderPedidos(){if(!$('listaPedidos'))return}
async function cambiarEstadoPedido(id,valor){if(dbOk)await db.collection('pedidos').doc(id).update({estadoPedido:valor})}
